config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    get "static_pages/home"
    get "static_pages/help"
    get "/signup", to: "users#new"
    post "/signup", to: "users#create"
    resources :users
    resources :account_activations, only: %i(edit)
    resources :password_resets, except: %i(index show destroy)
    resources :microposts, only: %i(create destroy)
    resources :users do
      member do
        get :following, :followers
      end
    end
    resources :relationships, only: %i(create destroy)
    get "/login", to: "session#new"
    post "/login", to: "session#create"
    delete "logout", to: "session#destroy"
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new; end

  def create
    user = User.find_by email: params[:session][:email].downcase
    if user&.authenticate params[:session][:password]
      handle_activated user
    else
      flash.now[:danger] = t "account.invalid_email_password_combination"
      render new
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to static_pages_home_path
  end

  private

  def handler_remember user
    if params[:session][:remember_me] == Settings.remember_status
      remember(user)
    else
      forget(user)
    end
  end

  def handle_activated user
    if user.activated?
      log_in user
      handler_remember user
      redirect_back_or user
    else
      message = t "message.not_activate"
      flash[:warning] = message
      redirect_to static_pages_home_path
    end
  end
end

app/helpers/session_helper.rb
module SessionHelper
  def log_in user
    session[:user_id] = user.id
  end

  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by id: user_id
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by id: user_id
      if user&.authenticated?(:remember, cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  def logged_in?
    current_user.present?
  end

  def remember user
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def forget user
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  def log_out
    current_user && forget(current_user)
    session.delete :user_id
    @current_user = nil
  end

  def redirect_back_or default
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end

  def current_user? user
    user == current_user
  end
end

app/views/session/new.html.erb
<% provide :title, t("account.login") %>
<% provide :title_base, t("title") %>
<h1 class="text-center"><%=t("account.login")%></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for :session, url: login_path do |f| %>
      <%= f.label :email, t("account.email") %>
      <%= f.email_field :email, class: "form-control" %>
      <%= f.label :password, t("account.password") %>
      <%= link_to t("account.forgot_pass"), new_password_reset_path %>
      <%= f.password_field :password, class: "form-control" %>
      <%= f.label :remember_me, class: "checkbox" do %>
        <%= f.check_box :remember_me %>
        <span><%=t("account.remember_me")%></span>
      <% end %>
      <%= f.submit t("account.login"), class: "btn btn-primary" %>
    <% end %>
    <p><%= t("account.new_user") %> <%= link_to t("account.signup"), signup_path %></p>
  </div>
</div>