config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    get "static_pages/home"
    get "static_pages/help"
    get "/signup", to: "users#new"
    post "/signup", to: "users#create"
    resources :users
    resources :account_activations, only: %i(edit)
    resources :password_resets, except: %i(index show destroy)
    resources :microposts, only: %i(create destroy)
    resources :users do
      member do
        get :following, :followers
      end
    end
    resources :relationships, only: %i(create destroy)
    get "/login", to: "session#new"
    post "/login", to: "session#create"
    delete "logout", to: "session#destroy"
  end
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to t("home.title"), static_pages_home_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to t("home_title"), static_pages_home_path %></li>
        <li><%= link_to t("help_title"), static_pages_help_path %></li>
        <% if logged_in? %>
          <li><%= link_to t("account.users"), users_path %></li>
          <li class="dropdown">
            <%= link_to "#", {class: "dropdown-toggle", data: {toggle: "dropdown"}} do %>
              <%= t("account.account") %>
              <b class="caret"></b>
            <% end %>
            <ul class="dropdown-menu">
              <li><%= link_to t("account.profile"), current_user %></li>
              <li><%= link_to t("account.setting"), edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li> <%= link_to t("account.logout"), logout_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to t("account.login"), login_path %></li>
        <% end %>
        <li><%= link_to t("locale.en"), locale: :en %></li>
        <li><%= link_to t("locale.vi"), locale: :vi %></li>
      </ul>
    </nav>
  <div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield(:title), yield(:title_base) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_pack_tag "application", "data-turbolinks-track": "reload" %>
  </head>
  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>